// 由 `pnpm --filter engine run art:install` 產生，不要手改。
//
// §6.4 的 `assets` 區塊：id → 檔案。**這是全專案唯一出現素材路徑的地方**——
// domain 只認 id，缺的走 AssetResolver 的 fallback（§6.3）。
// 想換整套美術，重跑一次 art:gen + art:install 就好，內容與規則零改動。
//
// 風格：dusk

export const coreTwAssets = {
  actors: {
    agent: '/art/actors/agent.webp',
    boss: '/art/actors/boss.webp',
    broker: '/art/actors/broker.webp',
    child: '/art/actors/child.webp',
    classmate: '/art/actors/classmate.webp',
    client: '/art/actors/client.webp',
    colleague_a: '/art/actors/colleague_a.webp',
    colleague_b: '/art/actors/colleague_b.webp',
    family: '/art/actors/family.webp',
    friend: '/art/actors/friend.webp',
    headhunter: '/art/actors/headhunter.webp',
    hr: '/art/actors/hr.webp',
    junior: '/art/actors/junior.webp',
    neighbour: '/art/actors/neighbour.webp',
    parent: '/art/actors/parent.webp',
    partner: '/art/actors/partner.webp',
    relative: '/art/actors/relative.webp',
    salesman: '/art/actors/salesman.webp',
    speaker: '/art/actors/speaker.webp',
    stranger: '/art/actors/stranger.webp',
  },
  bg: {
    airport: '/art/bg/airport.webp',
    apartment_block: '/art/bg/apartment_block.webp',
    bank: '/art/bg/bank.webp',
    banquet: '/art/bg/banquet.webp',
    bedroom_night: '/art/bg/bedroom_night.webp',
    cafe: '/art/bg/cafe.webp',
    car_dealer: '/art/bg/car_dealer.webp',
    city_skyline: '/art/bg/city_skyline.webp',
    classroom: '/art/bg/classroom.webp',
    clinic: '/art/bg/clinic.webp',
    community_center: '/art/bg/community_center.webp',
    commute: '/art/bg/commute.webp',
    conference: '/art/bg/conference.webp',
    countryside: '/art/bg/countryside.webp',
    data_center: '/art/bg/data_center.webp',
    empty_apartment: '/art/bg/empty_apartment.webp',
    empty_office: '/art/bg/empty_office.webp',
    fab: '/art/bg/fab.webp',
    factory: '/art/bg/factory.webp',
    factory_gate: '/art/bg/factory_gate.webp',
    family_home: '/art/bg/family_home.webp',
    harbour: '/art/bg/harbour.webp',
    home: '/art/bg/home.webp',
    home_desk: '/art/bg/home_desk.webp',
    hospital: '/art/bg/hospital.webp',
    lab: '/art/bg/lab.webp',
    life_start: '/art/bg/life_start.webp',
    market_street: '/art/bg/market_street.webp',
    meeting_room: '/art/bg/meeting_room.webp',
    night_classroom: '/art/bg/night_classroom.webp',
    night_market: '/art/bg/night_market.webp',
    office: '/art/bg/office.webp',
    office_night: '/art/bg/office_night.webp',
    old_apartment: '/art/bg/old_apartment.webp',
    pantry: '/art/bg/pantry.webp',
    park: '/art/bg/park.webp',
    parking_lot: '/art/bg/parking_lot.webp',
    phone: '/art/bg/phone.webp',
    restaurant: '/art/bg/restaurant.webp',
    school_gate: '/art/bg/school_gate.webp',
    seminar_hall: '/art/bg/seminar_hall.webp',
    shop_front: '/art/bg/shop_front.webp',
    startup_office: '/art/bg/startup_office.webp',
    street: '/art/bg/street.webp',
    street_food: '/art/bg/street_food.webp',
    street_night: '/art/bg/street_night.webp',
    study_room: '/art/bg/study_room.webp',
    temple: '/art/bg/temple.webp',
    trading_floor: '/art/bg/trading_floor.webp',
    warehouse: '/art/bg/warehouse.webp',
    wind_farm: '/art/bg/wind_farm.webp',
  },
  // 音效還沒有素材（TODO #5b）：缺檔就靜音，dev 模式印 would-play
  sfx: {},
}
