// §7.1 本遊戲的核心物件。二十四個機會，覆蓋十種主題與五種時代相位。
//
// 三條寫作紀律：
//
// 1. **暗示但不指名**（§2）。護國神山、某記憶體大廠、南部那間封測廠——
//    共鳴不減，法律與觀感風險為零。
// 2. **`truth` 玩家永遠看不到**（§7.1）。它在開倉當下才 roll 成實數，
//    而且受當時的時代調節。寫在這裡的是區間，不是結果。
// 3. **三版 signal 盡量寫滿**（§1.2）。低認知看到的是雜訊與人情，中認知看到
//    產業，高認知看到數字**與風險**。官方內容包同時是 mod 作者的示範，所以
//    這裡刻意不偷懶只寫一版。
//
// `sourcedBy` 的長度就是「有幾條路可以傳到你耳裡」——每條各擲一次，所以人脈
// 廣的人不只是機率高一點，而是通道多一條。

export const coreTwOpportunities = [
  // ── 人生級：一輩子遇不到幾次的那種 ────────────────────────────────────────
  {
    id: 'mem_supercycle_a',
    tier: 'life',
    window: { eraPhase: ['boom', 'mania'], themes: ['memory'] },
    require: { '>=': ['cognition', 25] },
    sourcedBy: ['colleague', 'broker', 'forum'],
    truth: { multiple: [4, 9], years: [2, 4], ruinChance: 20 },
    signal: {
      low: { text: '同事說這檔穩賺，他表哥在裡面做', reveal: [] },
      mid: { text: '做記憶體的，聽說產業要回溫了', reveal: ['theme'] },
      high: {
        text: '營收連三月雙位數成長、外資連買、本益比 12 倍，但客戶集中度偏高',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy', 'leveraged'],
    trials: ['drawdown_50', 'triple_temptation', 'family_emergency', 'everyone_says_sell'],
    scene: { bg: 'office_night', actor: 'colleague_a', sfx: 'phone_ring' },
  },
  {
    id: 'foundry_before_everyone',
    tier: 'life',
    window: { eraPhase: ['recovery', 'boom'], themes: ['memory', 'consumer'] },
    require: { all: [{ '>=': ['cognition', 30] }, { '>=': ['age', 26] }] },
    sourcedBy: ['colleague', 'classmate', 'forum'],
    truth: { multiple: [5, 13], years: [4, 8], ruinChance: 12 },
    signal: {
      low: { text: '那間代工廠聽說很缺人，股票應該不錯吧', reveal: [] },
      mid: { text: '晶圓代工這個模式好像只有他們做得起來', reveal: ['theme'] },
      high: {
        text: '毛利率年年墊高、客戶名單愈來愈長，資本支出大到沒有第二家追得上——但這種押注要抱十年',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy', 'leveraged'],
    trials: ['drawdown_50', 'lockup_years', 'better_offer_elsewhere', 'triple_temptation'],
    scene: { bg: 'fab', actor: 'classmate', sfx: 'cleanroom' },
  },
  {
    id: 'the_internet_thing',
    tier: 'life',
    window: { eraPhase: ['boom', 'mania'], themes: ['internet'] },
    require: { all: [{ '>=': ['cognition', 20] }, { '>=': ['network', 15] }] },
    sourcedBy: ['classmate', 'forum', 'client'],
    truth: { multiple: [2, 11], years: [1, 3], ruinChance: 45 },
    signal: {
      low: { text: '學弟說他們公司要上市了，現在進去就對了', reveal: [] },
      mid: { text: '做網路的，商業模式我聽不太懂，但大家都在投', reveal: ['theme'] },
      high: {
        text: '流量成長很漂亮，但沒有一年是賺錢的，估值算的是十年後的故事',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy', 'leveraged'],
    trials: ['triple_temptation', 'rumour_of_fraud', 'everyone_says_sell', 'drawdown_50'],
    scene: { bg: 'startup_office', actor: 'classmate', sfx: 'dialup' },
  },
  {
    id: 'ai_buildout',
    tier: 'life',
    window: { eraPhase: ['recovery', 'boom', 'mania'], themes: ['ai'] },
    require: { all: [{ '>=': ['cognition', 35] }, { '>=': ['capital', 100] }] },
    sourcedBy: ['colleague', 'broker', 'forum', 'client'],
    truth: { multiple: [4, 10], years: [2, 5], ruinChance: 27 },
    signal: {
      low: { text: '現在什麼東西沾上那三個字母都會漲', reveal: [] },
      mid: { text: '算力的需求好像是真的，機櫃排到明年', reveal: ['theme'] },
      high: {
        text: '訂單能見度兩年、毛利被上游吃掉一半，真正的問題是這波資本支出什麼時候停',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy', 'leveraged'],
    trials: ['drawdown_50', 'triple_temptation', 'paper_gains_tax', 'everyone_says_sell'],
    scene: { bg: 'data_center', actor: 'colleague_b', sfx: 'server_hum' },
  },
  {
    id: 'the_family_land',
    tier: 'life',
    window: { eraPhase: [], themes: ['property'] },
    require: { all: [{ '>=': ['age', 34] }, { '>=': ['capital', 150] }] },
    sourcedBy: ['family', 'neighbour'],
    truth: { multiple: [2.5, 6], years: [5, 10], ruinChance: 14 },
    signal: {
      low: { text: '長輩說那塊地將來一定會發', reveal: [] },
      mid: { text: '重劃區的邊上，聽說捷運會經過', reveal: ['theme'] },
      high: {
        text: '都市計畫的文件確實把它劃進去了，但變更程序走完通常是七到十年，中間完全不能動用',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['normal', 'heavy'],
    trials: ['lockup_years', 'family_emergency', 'better_offer_elsewhere'],
    scene: { bg: 'countryside', actor: 'relative' },
  },
  {
    id: 'shipping_supercycle',
    tier: 'life',
    window: { eraPhase: ['boom', 'mania'], themes: ['shipping'] },
    require: { all: [{ '>=': ['cognition', 22] }, { '>=': ['nerve', 45] }] },
    sourcedBy: ['broker', 'forum', 'client'],
    truth: { multiple: [3, 8], years: [1, 3], ruinChance: 35 },
    signal: {
      low: { text: '報紙說一個貨櫃的價格翻了五倍', reveal: [] },
      mid: { text: '塞港還沒解決，運價看起來還會撐一陣子', reveal: ['theme'] },
      high: {
        text: '現金流好到嚇人，但這是景氣循環股——你要賭的是「什麼時候下船」，不是「它值多少」',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy', 'leveraged'],
    trials: ['triple_temptation', 'everyone_says_sell', 'drawdown_50'],
    scene: { bg: 'harbour', actor: 'client', sfx: 'ship_horn' },
  },

  // ── 一般級：一次結算，不進逐年考驗 ──────────────────────────────────────
  {
    id: 'friend_noodle_shop',
    tier: 'normal',
    window: { eraPhase: [], themes: [] },
    require: { all: [{ '>=': ['age', 26] }, { '>=': ['network', 12] }, { '>=': ['capital', 40] }] },
    sourcedBy: ['friend', 'neighbour'],
    truth: { multiple: [0.4, 3.5], years: [2, 4], ruinChance: 30 },
    signal: {
      low: { text: '朋友要開店，問你要不要入一股', reveal: [] },
      mid: { text: '他做這行十年了，位置也挑得不錯', reveal: [] },
      high: {
        text: '客單價與租金算得過來，但餐飲的失敗率一向不看好人品看現金流',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal'],
    trials: [],
    scene: { bg: 'street_food', actor: 'friend' },
  },
  {
    id: 'panel_capex_race',
    tier: 'normal',
    window: { eraPhase: ['boom'], themes: ['memory', 'consumer'] },
    require: { '>=': ['cognition', 18] },
    sourcedBy: ['colleague', 'broker'],
    truth: { multiple: [0.6, 2.8], years: [2, 3], ruinChance: 28 },
    signal: {
      low: { text: '面板廠一直蓋新廠，看起來很有前途', reveal: [] },
      mid: { text: '這個產業每隔幾年就一次殺價競爭', reveal: ['theme'] },
      high: {
        text: '產能開出來的時間點全部撞在一起，報價撐不到明年下半年',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'factory', sfx: 'machine' },
  },
  {
    id: 'biotech_phase_two',
    tier: 'normal',
    window: { eraPhase: ['recovery', 'boom', 'mania'], themes: ['biotech'] },
    require: { all: [{ '>=': ['cognition', 28] }, { '>=': ['nerve', 40] }] },
    sourcedBy: ['classmate', 'broker', 'forum'],
    truth: { multiple: [0.2, 7], years: [2, 4], ruinChance: 50 },
    signal: {
      low: { text: '新藥要過了，過了就翻十倍', reveal: [] },
      mid: { text: '二期數據不錯，但三期才是真正的關卡', reveal: ['theme'] },
      high: {
        text: '樣本數偏小、對照組設計有爭議，三期失敗的話這家公司就沒有第二個產品',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'lab', actor: 'classmate' },
  },
  {
    id: 'green_energy_grid',
    tier: 'normal',
    window: { eraPhase: ['recovery', 'boom'], themes: ['energy'] },
    require: { '>=': ['cognition', 20] },
    sourcedBy: ['client', 'broker', 'forum'],
    truth: { multiple: [0.8, 4], years: [3, 6], ruinChance: 22 },
    signal: {
      low: { text: '政策要推的東西，跟著政策走準沒錯', reveal: [] },
      mid: { text: '電網與儲能的訂單看起來是十年的事', reveal: ['theme'] },
      high: {
        text: '案場一個一個標，毛利穩定但成長慢；真正的風險是躉購費率被砍',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'wind_farm' },
  },
  {
    id: 'bank_merger_play',
    tier: 'normal',
    window: { eraPhase: ['recovery', 'boom'], themes: ['finance'] },
    require: { all: [{ '>=': ['network', 20] }, { '>=': ['capital', 60] }] },
    sourcedBy: ['colleague', 'broker'],
    truth: { multiple: [0.9, 2.6], years: [1, 3], ruinChance: 18 },
    signal: {
      low: { text: '有人說那家要被併了', reveal: [] },
      mid: { text: '金控整併的風聲，這幾年一直有', reveal: ['theme'] },
      high: {
        text: '淨值比低於同業、大股東持股鬆動，但併購案卡在主管機關已經兩年',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'bank', actor: 'broker' },
  },
  {
    id: 'crypto_early',
    tier: 'normal',
    window: { eraPhase: ['boom', 'mania'], themes: ['crypto'] },
    require: { all: [{ '>=': ['cognition', 25] }, { '>=': ['nerve', 50] }] },
    sourcedBy: ['forum', 'classmate'],
    truth: { multiple: [0.05, 14], years: [1, 4], ruinChance: 55 },
    signal: {
      low: { text: '有人說這是下一個網際網路', reveal: [] },
      mid: { text: '技術本身挺有意思，但價格跟技術好像沒什麼關係', reveal: ['theme'] },
      high: {
        text: '沒有現金流可以評價，價格完全由資金面決定；交易所本身就是最大的風險',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'phone', sfx: 'notification' },
  },
  {
    id: 'old_apartment_renovation',
    tier: 'normal',
    window: { eraPhase: [], themes: ['property'] },
    require: { all: [{ '>=': ['age', 30] }, { '>=': ['capital', 120] }] },
    sourcedBy: ['neighbour', 'broker'],
    truth: { multiple: [0.9, 2.4], years: [2, 5], ruinChance: 16 },
    signal: {
      low: { text: '老公寓便宜，整理一下就能賣', reveal: [] },
      mid: { text: '這一區的成交價這兩年在動', reveal: ['theme'] },
      high: {
        text: '單價比周邊低兩成、但屋齡四十年管線全要換，裝修預算通常會超支五成',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['normal', 'heavy'],
    trials: [],
    scene: { bg: 'old_apartment' },
  },
  {
    id: 'supplier_equity_swap',
    tier: 'normal',
    window: { eraPhase: [], themes: [] },
    require: { all: [{ '>=': ['career.rank', 2] }, { '>=': ['network', 25] }] },
    sourcedBy: ['client', 'colleague'],
    truth: { multiple: [0.7, 4.5], years: [3, 6], ruinChance: 25 },
    signal: {
      low: { text: '客戶問你要不要順便入股', reveal: [] },
      mid: { text: '他們的訂單有一半來自你們公司', reveal: [] },
      high: {
        text: '你比任何分析師都清楚他們的良率與交期——問題是你也清楚那個客戶集中度',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'factory', actor: 'client' },
  },
  {
    id: 'index_fund_boring',
    tier: 'normal',
    window: { eraPhase: [], themes: [] },
    require: { '>=': ['age', 22] },
    sourcedBy: ['forum', 'broker', 'colleague'],
    truth: { multiple: [1.1, 3.2], years: [5, 10], ruinChance: 3 },
    signal: {
      low: { text: '有人說買整個市場就好，聽起來很沒意思', reveal: [] },
      mid: { text: '不用選股，長期報酬贏過大部分主動操作', reveal: [] },
      high: {
        text: '費用低、分散、你唯一要做的事是活得夠久而且不要中途賣掉',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'home_desk' },
  },
  {
    id: 'distressed_after_crash',
    tier: 'normal',
    window: { eraPhase: ['crash', 'recession'], themes: [] },
    require: { all: [{ '>=': ['cognition', 30] }, { '>=': ['nerve', 45] }, { '>=': ['capital', 60] }] },
    sourcedBy: ['broker', 'colleague', 'forum'],
    truth: { multiple: [1.2, 6], years: [3, 6], ruinChance: 20 },
    signal: {
      low: { text: '跌成這樣，隨便買都會賺吧', reveal: [] },
      mid: { text: '有些公司的股價已經低於手上的現金了', reveal: [] },
      high: {
        text: '淨現金高於市值、本業還在賺；風險是大股東可能自己把它下市買回去',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy', 'leveraged'],
    trials: [],
    scene: { bg: 'trading_floor', fx: 'red_screen' },
  },
  {
    id: 'classmate_startup',
    tier: 'normal',
    window: { eraPhase: ['recovery', 'boom', 'mania'], themes: ['internet', 'ai'] },
    require: { all: [{ '>=': ['network', 22] }, { '>=': ['capital', 50] }] },
    sourcedBy: ['classmate', 'friend'],
    truth: { multiple: [0.05, 11], years: [4, 8], ruinChance: 60 },
    signal: {
      low: { text: '同學說他在做一個很大的東西，缺一點錢', reveal: [] },
      mid: { text: '團隊看起來不錯，產品還在很早期', reveal: ['theme'] },
      high: {
        text: '有真的付費客戶，但只有三個；這種投資十件裡面九件會歸零，剩下那件要能扛住前面九件',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal'],
    trials: [],
    scene: { bg: 'startup_office', actor: 'classmate' },
  },
  {
    id: 'gold_and_fear',
    tier: 'normal',
    window: { eraPhase: ['crash', 'recession'], themes: ['energy', 'finance'] },
    require: { '>=': ['age', 30] },
    sourcedBy: ['family', 'broker'],
    truth: { multiple: [0.9, 2.2], years: [2, 5], ruinChance: 10 },
    signal: {
      low: { text: '長輩說錢要換成看得到的東西', reveal: [] },
      mid: { text: '避險資產在這種時候通常會撐住', reveal: ['theme'] },
      high: {
        text: '它不生任何現金流，只在別人恐懼時有價值——所以它保的是本金，不是報酬',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal'],
    trials: [],
    scene: { bg: 'bank', actor: 'parent' },
  },
  {
    id: 'passive_component_squeeze',
    tier: 'normal',
    window: { eraPhase: ['boom', 'mania'], themes: ['memory', 'consumer'] },
    require: { '>=': ['cognition', 24] },
    sourcedBy: ['colleague', 'broker', 'forum'],
    truth: { multiple: [0.4, 6 ], years: [1, 2], ruinChance: 38 },
    signal: {
      low: { text: '那個零件現在缺到有錢買不到', reveal: [] },
      mid: { text: '報價一週一個樣，通路商在囤貨', reveal: ['theme'] },
      high: {
        text: '缺貨是真的，但擴產只要一年；這種行情的頂點通常出現在報價還在漲的時候',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'warehouse' },
  },
  {
    id: 'franchise_licence',
    tier: 'normal',
    window: { eraPhase: ['recovery', 'boom'], themes: ['consumer'] },
    require: { all: [{ '>=': ['age', 32] }, { '>=': ['capital', 100] }, { '>=': ['nerve', 50] }] },
    sourcedBy: ['friend', 'client'],
    truth: { multiple: [0.5, 3 ], years: [3, 6], ruinChance: 28 },
    signal: {
      low: { text: '那個牌子現在很紅，聽說加盟很好賺', reveal: [] },
      mid: { text: '總部提供供應鏈，但抽成不低', reveal: ['theme'] },
      high: {
        text: '單店回本要四年，而合約只簽五年；真正賺錢的是賣加盟權的那一方',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['normal', 'heavy'],
    trials: [],
    scene: { bg: 'shop_front', actor: 'friend' },
  },
  {
    id: 'colleague_pre_ipo',
    tier: 'normal',
    window: { eraPhase: ['boom', 'mania'], themes: [] },
    require: { all: [{ '>=': ['network', 28] }, { '>=': ['capital', 80] }] },
    sourcedBy: ['colleague', 'client', 'broker'],
    truth: { multiple: [0.3, 7], years: [2, 4], ruinChance: 40 },
    signal: {
      low: { text: '有未上市的額度，很多人搶', reveal: [] },
      mid: { text: '公司說明年送件，承銷商已經找好了', reveal: [] },
      high: {
        text: '未上市盤的價格是喊出來的；送件到掛牌至少兩年，中間你連賣的地方都沒有',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal'],
    trials: [],
    scene: { bg: 'office', actor: 'colleague_b' },
  },
  {
    id: 'the_boring_landlord',
    tier: 'normal',
    window: { eraPhase: [], themes: ['property', 'finance'] },
    require: { all: [{ '>=': ['age', 38] }, { '>=': ['capital', 200] }] },
    sourcedBy: ['neighbour', 'broker'],
    truth: { multiple: [1.1, 2.5], years: [5, 9], ruinChance: 8 },
    signal: {
      low: { text: '收租嘛，每個月都有錢進來', reveal: [] },
      mid: { text: '租金報酬率不高，但很穩', reveal: ['theme'] },
      high: {
        text: '兩趴多的租金報酬率打不過通膨，真正的獲利來自槓桿與時間——前提是你撐得住空租',
        reveal: ['theme', 'valuation', 'risk'],
      },
    },
    sizing: ['normal', 'heavy', 'leveraged'],
    trials: [],
    scene: { bg: 'apartment_block' },
  },
  {
    id: 'second_hand_machine',
    tier: 'normal',
    window: { eraPhase: ['recession', 'recovery'], themes: [] },
    require: { all: [{ in: ['career.industry', ['factory', 'trade', 'own']] }, { '>=': ['capital', 60] }] },
    sourcedBy: ['client', 'colleague'],
    truth: { multiple: [0.8, 3.4], years: [2, 4], ruinChance: 20 },
    signal: {
      low: { text: '有人倒了，機器在賤賣', reveal: [] },
      mid: { text: '這種設備平常買不到這個價', reveal: [] },
      high: {
        text: '折舊算下來三年回本，但你要有訂單餵它——沒有訂單它就是一塊很貴的鐵',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal', 'heavy'],
    trials: [],
    scene: { bg: 'factory', sfx: 'machine' },
  },
  {
    id: 'night_market_stall',
    tier: 'normal',
    window: { eraPhase: [], themes: ['consumer'] },
    require: { all: [{ '>=': ['age', 22] }, { '>=': ['capital', 25] }, { '>=': ['nerve', 45] }] },
    sourcedBy: ['friend', 'neighbour', 'family'],
    truth: { multiple: [0.5, 3.8], years: [1, 3], ruinChance: 30 },
    signal: {
      low: { text: '晚上去顧攤，賺的都是現金', reveal: [] },
      mid: { text: '位置好的攤位不容易租到', reveal: [] },
      high: {
        text: '毛利很高但全靠人力；真正決定成敗的是你願不願意連續三年每晚站六小時',
        reveal: ['valuation', 'risk'],
      },
    },
    sizing: ['light', 'normal'],
    trials: [],
    scene: { bg: 'night_market', sfx: 'crowd' },
  },
]
