// §7.5 投資人格：**行為的函數，不是隨機掉落**。
//
// 每一條 require 讀的都是 counter.*——引擎自己維護的（held_through_drawdown、
// dice_study、experience_years…）與內容自己累積的（did_homework、followed_tip、
// frugal…）在條件樹裡沒有任何區別。這就是為什麼第三方內容包能長出自己的人格。
//
// `exclude` 是互斥：新拿到的勝出，被取代的進 removed[]（結算畫面上會畫刪除線）。
// `checkOn` 決定什麼時候檢查，是資料不是程式——改一個字就改變解鎖時機。

export const coreTwTraits = [
  // ── 市場行為 ──────────────────────────────────────────────────────────────
  {
    id: 'diamond_hands',
    name: '鑽石手',
    tone: 'gold',
    require: {
      all: [{ '>=': ['counter.held_through_drawdown', 3] }, { '<=': ['counter.panic_sold', 0] }],
    },
    exclude: ['retail_leek'],
    grants: [{ type: 'stat.add', key: 'nerve', value: 10 }],
    text: '帳面腰斬三次，你一股都沒賣。市場的噪音再也動不了你。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end', 'position.close'],
  },
  {
    id: 'retail_leek',
    name: '韭菜',
    tone: 'bad',
    require: { all: [{ '>=': ['counter.panic_sold', 2] }, { '>=': ['counter.followed_tip', 2] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 2 }],
    text: '追高、殺低、聽明牌。你付的學費夠買一台車了——但你確實學到了東西。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end', 'position.close'],
  },
  {
    id: 'contrarian_soul',
    name: '逆向者',
    tone: 'gold',
    require: { all: [{ '>=': ['counter.contrarian', 2] }, { '>=': ['counter.survived_crash', 1] }] },
    exclude: ['trend_chaser'],
    grants: [{ type: 'stat.add', key: 'cognition', value: 5 }],
    text: '你在所有人都在賣的時候買。不是因為勇敢，是因為你算過。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'trend_chaser',
    name: '追高的人',
    tone: 'bad',
    require: { '>=': ['counter.chased_top', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: -5 }],
    text: '每一波你都在，只是每一波都在最後才進去。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'leverage_gambler',
    name: '槓桿賭徒',
    tone: 'bad',
    require: { flag: 'leveraged_wipeout' },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: -10 }],
    text: '你借來的錢曾經讓你看起來很像天才。',
    scene: { fx: 'trait_unlock', sfx: 'thud' },
    checkOn: ['turn.end', 'position.close'],
  },
  {
    id: 'homework_habit',
    name: '做功課的人',
    tone: 'good',
    require: { '>=': ['counter.did_homework', 4] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 6 }],
    text: '你讀完的那些附註，別人都跳過。差別要十年才看得出來。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'tip_follower',
    name: '聽明牌的',
    tone: 'bad',
    require: { '>=': ['counter.followed_tip', 6] },
    exclude: ['homework_habit'],
    grants: [{ type: 'stat.add', key: 'network', value: 3 }],
    text: '你認識很多人，每個人都有一檔要跟你講。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'sat_on_hands',
    name: '什麼都不做的人',
    tone: 'gold',
    require: { all: [{ '>=': ['counter.did_nothing', 3] }, { '>=': ['age', 45] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 8 }],
    text: '你這輩子最賺錢的決定，是那幾年什麼都沒做。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'dividend_farmer',
    name: '收租的人',
    tone: 'good',
    require: { '>=': ['counter.dividend_years', 4] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'savingsRate', value: 0.03 }],
    text: '一年一次的入帳，四十年就是四十次。你從來沒有錯過。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'crisis_veteran',
    name: '倖存者',
    tone: 'gold',
    require: { '>=': ['counter.survived_crash', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 12 }],
    text: '你經歷過三次崩盤，而且每一次都還在。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'early_bird',
    name: '早到的人',
    tone: 'gold',
    require: { '>=': ['counter.early_adopter', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 4 }],
    text: '你在別人還在笑的時候就進去了。當然，你也曾經笑錯過。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'scar_tissue',
    name: '疤痕組織',
    tone: 'neutral',
    require: { '>=': ['counter.market_lessons', 7] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 8 }],
    text: '你交過的學費夠讀一個學位。差別是這個學位不能掛在牆上。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end', 'position.close'],
  },
  {
    id: 'conviction_player',
    name: '有信念的人',
    tone: 'gold',
    require: { all: [{ '>=': ['counter.conviction', 1] }, { '>=': ['counter.did_homework', 3] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 8 }],
    text: '你重押的那一次，是二十年的準備換來的。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['position.close', 'turn.end'],
  },
  {
    id: 'made_peace',
    name: '放得下',
    tone: 'good',
    require: { all: [{ '>=': ['counter.let_it_go', 1] }, { '>=': ['counter.opportunities_declined', 2] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 10 }],
    text: '錯過的那幾次，你沒有再回頭看。這比抓住更難。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'ice_in_veins',
    name: '冷血',
    tone: 'gold',
    require: { all: [{ '>=': ['counter.kept_cool', 1] }, { '>=': ['counter.trials_faced', 3] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 15 }],
    text: '考驗來的時候，你的心跳跟平常一樣。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['event.resolve', 'position.close'],
  },

  // ── 工作與人 ──────────────────────────────────────────────────────────────
  {
    id: 'night_scholar',
    name: '夜讀者',
    tone: 'good',
    require: { '>=': ['counter.night_study', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 6 }],
    text: '白天上班，晚上念書。那幾年的燈是你自己開的。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'the_one_who_stayed',
    name: '扛下來的人',
    tone: 'gold',
    require: { '>=': ['counter.took_the_blame', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'network', value: 10 }],
    text: '出事的時候你站在前面。從那之後，他們願意為你做任何事。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'the_mentor',
    name: '帶人的人',
    tone: 'good',
    require: { any: [{ '>=': ['counter.mentored', 3] }, { '>=': ['counter.taught_well', 3] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'network', value: 8 }],
    text: '你帶過的人散在各個公司。這是最慢、也最可靠的一種人脈。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'career_climber',
    name: '往上爬的人',
    tone: 'good',
    require: { all: [{ '>=': ['counter.career_moves', 5] }, { '>=': ['career.rank', 4] }] },
    exclude: ['lifer'],
    grants: [{ type: 'stat.add', key: 'income', value: 10 }],
    text: '每一次換位置你都算得很清楚。你不是不忠誠，你只是很清醒。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'lifer',
    name: '守著一個位置的人',
    tone: 'neutral',
    require: { all: [{ '>=': ['counter.experience_years', 25] }, { '<=': ['counter.career_moves', 1] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 10 }],
    text: '二十五年同一個地方。有人說你沒野心，但你知道那不是全部的故事。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'burned_out',
    name: '燒完了',
    tone: 'bad',
    require: { '>=': ['counter.burnout', 2] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: -8 }],
    text: '有一年你發現自己不記得上一次期待星期一是什麼時候。',
    scene: { fx: 'trait_unlock', sfx: 'thud' },
    checkOn: ['turn.end'],
  },
  {
    id: 'side_hustler',
    name: '做副業的人',
    tone: 'good',
    require: { '>=': ['counter.side_hustle', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'income', value: 6 }],
    text: '本業之外那條線，最後變成你真正的安全感。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'grey_area',
    name: '灰色地帶',
    tone: 'bad',
    require: { '>=': ['counter.crossed_the_line', 1] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: -6 }],
    text: '有一次你走過那條線。錢是真的，那個晚上也是真的。',
    scene: { fx: 'trait_unlock', sfx: 'thud' },
    checkOn: ['turn.end'],
  },

  // ── 錢與生活 ──────────────────────────────────────────────────────────────
  {
    id: 'frugal_by_nature',
    name: '省得下來的人',
    tone: 'good',
    require: { '>=': ['counter.frugal', 3] },
    exclude: ['big_spender'],
    grants: [{ type: 'stat.add', key: 'savingsRate', value: 0.05 }],
    text: '你不是不敢花，是知道那些錢在別的地方比較有用。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'big_spender',
    name: '會過日子的人',
    tone: 'neutral',
    require: { '>=': ['counter.splurge', 3] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 8 }],
    text: '你買過幾樣不必要的東西，而它們讓那幾年變得可以忍受。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'family_anchor',
    name: '家裡那根柱子',
    tone: 'gold',
    require: { '>=': ['counter.family_first', 4] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 12 }],
    text: '有人生病、有人要學費、有人需要有人在。每次都是你。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'debt_survivor',
    name: '從債裡爬出來的人',
    tone: 'gold',
    require: { all: [{ '>=': ['counter.years_in_debt', 4] }, { '<=': ['debt', 0] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 15 }],
    text: '你欠過錢，也還完了。這件事會改變一個人看數字的方式。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'body_debt',
    name: '欠身體的',
    tone: 'bad',
    require: { '>=': ['counter.health_debt', 4] },
    exclude: ['still_running'],
    grants: [{ type: 'stat.add', key: 'nerve', value: -10 }],
    text: '你用健康換了幾年的收入。帳單會在後面等你。',
    scene: { fx: 'trait_unlock', sfx: 'thud' },
    checkOn: ['turn.end'],
  },
  {
    id: 'still_running',
    name: '還在跑的人',
    tone: 'good',
    require: { all: [{ '>=': ['counter.keeps_fit', 3] }, { '>=': ['age', 45] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 10 }],
    text: '四十五歲之後，體力本身就是一種資本。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'lucky_break',
    name: '拿過一次好牌',
    tone: 'neutral',
    require: { '>=': ['counter.windfall', 1] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 2 }],
    text: '有一筆錢不是你賺來的。你花了很久才想清楚該怎麼看待它。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'planner',
    name: '會算的人',
    tone: 'good',
    require: { '>=': ['counter.planned_ahead', 2] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'cognition', value: 4 }],
    text: '你算過退休那天的數字，而且不只算過一次。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'legacy',
    name: '把它傳下去的人',
    tone: 'gold',
    require: { any: [{ '>=': ['counter.passed_it_on', 1] }, { '>=': ['counter.taught_investing', 2] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: 10 }],
    text: '你教的不是明牌，是那幾次你怎麼撐過來的。',
    scene: { fx: 'trait_unlock', sfx: 'chime' },
    checkOn: ['turn.end'],
  },
  {
    id: 'the_gambler',
    name: '賭性',
    tone: 'bad',
    require: { '>=': ['counter.gambles', 6] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: -4 }],
    text: '你喜歡那個開獎前的三秒鐘。承認吧，那才是你買的東西。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'the_bold_one',
    name: '每次都選最猛的',
    tone: 'neutral',
    require: { all: [{ '>=': ['counter.chose_bold', 12] }, { '>=': ['age', 40] }] },
    exclude: ['the_careful_one'],
    grants: [{ type: 'stat.add', key: 'nerve', value: 6 }],
    text: '人生給你三個選項的時候，你的手總是伸向最右邊那個。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['event.resolve'],
  },
  {
    id: 'the_careful_one',
    name: '每次都選最穩的',
    tone: 'neutral',
    require: { all: [{ '>=': ['counter.chose_safe', 15] }, { '>=': ['age', 40] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'savingsRate', value: 0.04 }],
    text: '你這輩子沒有做過什麼驚人的決定。你也沒有輸掉什麼。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['event.resolve'],
  },
  {
    id: 'insomniac',
    name: '睡不著的人',
    tone: 'bad',
    require: { '>=': ['counter.insomnia', 2] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'nerve', value: -6 }],
    text: '半夜三點的那些數字，你比誰都熟。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
  {
    id: 'good_neighbour',
    name: '會被找的人',
    tone: 'good',
    require: { any: [{ '>=': ['counter.helped_others', 3] }, { '>=': ['counter.lent_money', 3] }] },
    exclude: [],
    grants: [{ type: 'stat.add', key: 'network', value: 8 }],
    text: '有事的時候，別人想到的是你。這件事本身就是一種資產。',
    scene: { fx: 'trait_unlock' },
    checkOn: ['turn.end'],
  },
]
